<refentry id="{@id}">
  <refnamediv>
    <refname>SearchPageBase class description</refname>
    <refpurpose></refpurpose>
  </refnamediv>
  <refsynopsisdiv>
    <author>papaya Software GmbH</author>
  </refsynopsisdiv>
  {@toc}
  <refsect1 id="{@id search-page}">
    <title>Introduction</title>
    <para>
      The livesearch page class extends the papaya {@link base_content} class and is used to generate 
      the specific outpout needed by a suggestion functionality.
    </para>
  </refsect1>
  <refsect1 id="{@id class-member}">
    <title>Class member</title>
    <para>
      This section includes the description of the class members.
    </para>
  </refsect1>
  <refsect1 id="{@id class-methods}">
    <title>Class methods</title>
    <para>
      This section includes the description of the class methods.
    </para>
  </refsect1>
</refentry>