<refentry id="{@id}">
  <refnamediv>
    <refname>Description for the SearchInterfaceDataprovider class</refname>
    <refpurpose>Interface definition for search dataproviders</refpurpose>
  </refnamediv>
  <refsynopsisdiv>
    <author>papaya Software GmbH</author>
  </refsynopsisdiv>
  {@toc}
  <refsect1 id="{@id search}">
    <title>Introduction</title>
    <para>
      TBD
    </para>
  </refsect1>
</refentry>